### ISSUE TITLE
Looking for the Tabor Hero Block plugin

### ISSUE THREAD

**Issue by cramdesign** [themebeans/tabor#1]
I am getting this message (I removed the name of my home folder but it is my server):

Installing Plugin: Tabor Hero Block
Downloading installation package from [my home folder here]/media/wp/wp-content/themes/tabor/inc/plugins/tabor-blocks.zip…

Download failed. A valid URL was not provided.

**Comment by richtabor** [comment]
Thanks @cramdesign — fixed!
