### ISSUE TITLE
Is there a way to permanently enable night mode?

### ISSUE THREAD

**Issue by sam33256** [themebeans/tabor#8]
I want to completely disable 'day' mode so that my visitors only see the night mode version of the site and also don't see the button. Is that possible?

**Comment by richtabor** [comment]
Not out of the box, but you could add the `night-mode` class to the `html` element in the theme (or better yet, child theme) and it'll do the trick. 

![night](https://user-images.githubusercontent.com/1813435/72628414-46540380-391c-11ea-9ef9-11a24a539bff.gif)
